version: '3'

services:
  locust:
    build:
      context: ./user-service/loadtest
    ports:
      - 8089:8089
    networks:
      - microservices_network
    depends_on:
      - api-gateway-container
    environment:
      - LOCUST_USERS=100
      - LOCUST_SPAWN_RATE=10
      - LOCUST_RUN_TIME=5m
      - TARGET_HOST=http://api-gateway-container:8080
    command: sh -c "locust -f locustfile.py --host ${TARGET_HOST} --web-host 0.0.0.0 --web-port 8089"

networks:
  microservices_network:
    driver: bridge
