version: '3.3'

services:
  locust:
    image: locustio/locust:2.16.0
    restart: unless-stopped
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py:ro
    ports:
      - "8089:8089" 
    environment:
      - TARGET_HOST=${TARGET_HOST:-http://host.docker.internal:8080}
    command: -f /mnt/locust/locustfile.py --host ${TARGET_HOST:-http://host.docker.internal:8080}
