substitutions:
  _CLUSTER_NAME: "mi-primer-cluster-taller"
  _CLUSTER_ZONE: "us-central1"
  _NAMESPACE: "stage"

steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-gateway:$SHORT_SHA', '-f', 'api-gateway/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-config:$SHORT_SHA', '-f', 'cloud-config/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/service-discovery:$SHORT_SHA', '-f', 'service-discovery/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proxy-client:$SHORT_SHA', '-f', 'proxy-client/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/user-service:$SHORT_SHA', '-f', 'user-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/product-service:$SHORT_SHA', '-f', 'product-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/order-service:$SHORT_SHA', '-f', 'order-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/payment-service:$SHORT_SHA', '-f', 'payment-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/favourite-service:$SHORT_SHA', '-f', 'favourite-service/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/shipping-service:$SHORT_SHA', '-f', 'shipping-service/Dockerfile', '.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud container clusters get-credentials ${_CLUSTER_NAME} --zone ${_CLUSTER_ZONE} --project ${PROJECT_ID}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'kubectl create namespace ${_NAMESPACE} || true']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'for f in k8s/staging/*.yml; do sed -i "s|IMAGE_TAG|${SHORT_SHA}|g" "$f"; sed -i "s|PROJECT_ID|${PROJECT_ID}|g" "$f"; done']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'kubectl apply -n ${_NAMESPACE} -f k8s/staging/core.yml']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'kubectl -n ${_NAMESPACE} wait --for=condition=available deployment/zipkin --timeout=120s']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'kubectl -n ${_NAMESPACE} wait --for=condition=available deployment/service-discovery --timeout=120s']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'kubectl -n ${_NAMESPACE} wait --for=condition=available deployment/cloud-config --timeout=120s']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'kubectl apply -n ${_NAMESPACE} -f k8s/staging/compose.yml']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'kubectl -n ${_NAMESPACE} wait --for=condition=available --all deployments --timeout=1500s']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'kubectl -n ${_NAMESPACE} delete pod stage-tester --ignore-not-found']


images:
  - 'gcr.io/$PROJECT_ID/api-gateway:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/cloud-config:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/service-discovery:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/proxy-client:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/user-service:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/product-service:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/order-service:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/payment-service:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/favourite-service:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/shipping-service:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
