
name: Prod, on PUSH Java CI/CD of favourite-service-ecommerce-boot, ecommerce-microservice-backend app

on:
  push:
    branches: [ master ]

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests # Skip tests during package, run explicitly later
    - name: Run Unit Tests
      run: mvn -B test --file pom.xml
    - name: Setup env variables for Docker
      run: echo Setup env variables for Docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build Docker image for favourite-service-ecommerce-boot Microservice
      run: docker build -f favourite-service/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/favourite-service-ecommerce-boot:${{ secrets.PROJECT_VERSION }} .
    - name: Push favourite-service-ecommerce-boot image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/favourite-service-ecommerce-boot:${{ secrets.PROJECT_VERSION }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Run Load Tests
      working-directory: favourite-service/loadtest
      run: |
        docker-compose pull
        docker-compose up -d
        # Give Locust some time to start and run tests. Adjust sleep duration as needed.
        echo "Waiting for load tests to run for 60 seconds..."
        sleep 60
        docker-compose down
    - name: Deploy to Kubernetes
      uses: azure/k8s-set-context@v1 # Assuming Azure Kubernetes Service based on azure-pipelines.yml
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }} # Kubeconfig secret
    - run: kubectl apply -f k8s/staging/favourite-service-deployment.yaml
    - name: Generate Release Notes
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


